//en英文语言包 用雙引號取代單引號，因為所包覆的英文句子需要使用單引號，如：it's 或是重點單字都用單引號
export default {
    login: {
      welcome:"Welcome to Autonomous Learning 2.0(Auto20) non-profit friend search platform",
      hp:"Home page",
      ab:"About us",
      mp:"Map",
      fr:"Friends",
      gp:"Groups",
      fg:"My flag",
      hd:"Some are first in learning, and others excel in  different fields.",
      pr:" Privacy Policy ",
      bk: "My Directory",
      logout: "Logout",
      lm: "Learn more",
      login: "Login",
      go_flag: "Go to My Flag"
    },
    chat: {
      gc: "Chats",
      cp: "Shrink"
    },
    news: {
      upgrading: "We are upgrading",
      flag: "Please update your flag regularly",
      remove: "Flags that logged in with Facebook will be removed",
      // report: 'For any suggestions and bug reports, please go to this <a href="https://github.com/3dw/auto20-next/issues" target="_blank" rel="noopener noreferrer">issue area</a>'
    },
    about: {
      intro: " Introduction ",
      what_is_auto20: "What is Autonomous Learning 2.0(Auto20)?",
      auto20: "Autonomous Learning 2.0(Auto20)",
      intro_1: " is a public welfare friend-finding platform, free of charge and without advertising. It aims to help users find friends through geographical location, personal interests and expertise. The core function of the platform, 'Mutual Aid Flag', provides public self-introduction, allowing people to get to know each other initially before meeting.",
      al: "Autonomous Learning",
      intro_2: " is 'homeschooling' in the narrow sense and 'Self-directed learning' in the broad sense. Independent learning is an attitude of being responsible for one's own growth and life.",
      intro_3: "We welcome all friends who are interested in 'Self-directed Learning' to participate, regardless of age and whether they are in school or not.",
      auto20_by: "Who is designing and maintaining Autonomous Learning 2.0(Auto20)？",
      auto20_by_content1: "This platform is designed and maintained by",
      auto20_by_content2: " the non-profit organization Autonomous Learning Promotion Association of  R.O.C. (Taiwan)",
      auto20_by_content3: ", dedicated to providing a safe and friendly environment for everyone to freely find learning partners.",
      card_flag: "What is Cloud Card and Mutual Aid Flag?",
      card_name: "Cloud Card",
      card_content1: " is a self-introduction feature with an approximate geographical location, allowing others to have a preliminary understanding of your interests, expertise, and background before meeting you, making it easier to find like-minded friends.",
      flag_content1: "The system automatically assigns you an appropriate location on the map based on your approximate geographic location, like planting a flag. Hence, it is also called a 'Mutual Aid Flag'.",
      card_content2: "After you create a 'Cloud Card', the system will provide you with a unique URL that you can use for self-introduction.",
      qrcode_content1: "You will also receive a unique QR code that friends can scan with their mobile phones to link to your cloud card.",
      raise_flag: "Raise a Mutual Aid Flag",
      card_flag_tip: "Tips for Filling Out the Form to Raise the Flag",
      card_flag_tip_content: "'Interests', 'Sharing', and 'Seeking' are the three factors that influence the logical operation of the automatic matching program.To accurately match those in need with those who can help, please clearly fill in your interests, what you can share, and what you are seeking. You can use commas (','), Chinese commas ('，'), or slashes ('/') to separate multiple items.",
      flag_update1: "Does the 'Mutual Aid Flag' need to be updated?",
      flag_update_content: "To ensure that friends in need can find you smoothly, please update your 'Mutual Aid Flag' periodically, especially after moving.",
      flag_content2: "Will my 'Mutual Aid Flag' be public?",
      flag_content3: "The 'Mutual Aid Flag' is completely public, and you can choose to leave only the information you are willing to disclose. Please refer to our",
      flag_content4: " to learn how to better protect your privacy.",
      flag_update2: "Can I modify the 'Mutual Aid Flag' after raising it?",
      flag_content5: "Of course! Just log in to the platform again, click on 'My Flag', and you can modify the content of your 'Mutual Aid Flag' at any time to keep the information up-to-date and accurate.",
      flag_download: "Can I download a backup after raising the 'Mutual Aid Flag'?",
      flag_content6: "Of course! Just log in to the platform again, click on 'Privacy Policy', and click the 'Download Backup' button below to download your data backup.",
      pr_go: "Go to Privacy Policy",
      flag_remove: "Can I remove the 'Mutual Aid Flag' after raising it?",
      flag_content7: "Yes, you can. Simply go to the 'My Flag' page and click 'Delete Flag' to remove your flag and opt out Autonomous Learning 2.0(Auto20).",
      map_is: "What is the purpose of the 'Map'?",
      map_content1: "The 'Map' is designed to help you find friends who are geographically close to you. You can click on the flag icon on the map to view the 'Cloud Card' of the friend.",
      map_go: "Go to Map",
      directory_is: "What is the 'My Directory'?",
      directory_content1: " is a feature that allows you to manage and find specific friends easily, similar to shortcuts or pins. Users can create their own directory to easily find specific friends next time.",
      group_is: "What is the concept of 'Groups' in Autonomous Learning 2.0(Auto20)?",
      group_content1: " is similar to a resource pool. Users can create groups, add introductions, share learning resources, and chat. This helps to collect and share useful information according to the theme, and promote collaboration and interaction among members.",
      group_go: "Go to Groups",
      bugreport_is: "How to submit bug reports or feature requests?",
      bugreport_content1: " has a project issue tracker on Github. Please submit bug reports and feature requests on Github's project issue tracker. Thank you. If you don't have a Github account yet, please register a Github account first before leaving a message.",
      bugreport_content2: "Note: You do not need a Github account if you are only logging into Autonomous Learning 2.0(Auto20) and not submitting an issue.",
      bugreport_go: "Go to Project Issue Tracker",
      github_is: "What is Github?",
      github_content1: "Github is a platform for hosting and collaborating on software development projects. It is widely used for version control using Git. It also provides a platform for users to submit bug reports and feature requests.",
      github_go: "GitHub Tutorial for Beginners",
    },
    privacy: {
      title: ' Privacy Policy ',
      strong: 'In order to protect your personal privacy, please do not place any sensitive or too complete personally identifiable information on the mutual aid flag.'
    }
  }